[package]
name = "hwrep"
version = "0.1.0"
authors = ["Jay Palat <jay@palat.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
procfs = "0.8.1"
